version: '2'

services:
    application:
        container_name: pk_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: pk_workspace
        image: framgia/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: pk_php-fpm
        image: framgia/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: pk_nginx
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - application
        ports:
            - "2020:80"
        links:
            - php-fpm
    data:
        container_name: pk_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    mysql:
        container_name: pk_mysql
        image: mysql:5.7
        volumes_from:
            - data
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: pk
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: pk_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        links:
            - "mysql:mysql"
